### PR TITLE
Category page features

### LINKED ISSUE #788: Increase capabilities of category landing pages
Create space on category landing pages to feature relevant reporting from Other category or  Tracker cases.
--    Repurposes Other category into more reporting/blog-like function 
--     Features long-form writing/investigations that aren’t (necessarily) cases/part of data set
--    Highlights important cases (rather than by date “river”)
--    Space is curatable

### PR DESCRIPTION
**Pull request by chigby**
This pull request, essentially, duplicates the home page's ability to feature incidents/posts and applies it to category pages.  I've created some dev data too, to help test it out. The design is exactly the same as the home page's design, and I welcome comments for ways to make that better, if desired.

Fixes #788

### CODE REVIEW

**Review by SaptakS — APPROVED** [review]
This looks good to me.

**Comment by eloquence** [comment]
(Harris will touch base with Kirstin about this change, and then we'll potentially revisit.)

**Comment by harrislapiroff** [comment]
Confirmed that @KAMcCudden still wants these features, so moving it back to review.

**Comment by harrislapiroff** [comment]
We're going to retire this PR in favor of waiting for the redesign process to happen.

**Pull request closed without merging**
