### PR TITLE
Uses display name for case type

### LINKED ISSUE #1166: Render display value for Case Type in template
We should be rendering the display value (title cased) instead of the database value (all capsed) for case types on incident pages. Current appearance:

image

Should be `Type of case: Civil` instead.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #1166

### CODE REVIEW

**Comment by harrislapiroff** [comment]
@SaptakS Can you just add one more fix to this PR? The PFT editors want Case number, Case status, and Type of case to be at the bottom of the table—only Tags should be below it.

**Comment by harrislapiroff** [comment]
And also move type of case above the other two fields.

**Comment by SaptakS** [comment]
@harrislapiroff done!

**Comment by harrislapiroff** [comment]
@SaptakS Am I correct that this PR is no longer relevant with the redesign? If so, go ahead and close it, sorry for the extra work 😅

**Pull request closed without merging**
