### PR TITLE
Charts cleanup, comments, and bugfixes

### PR DESCRIPTION
**Pull request by dkaoster**
## Description
Did a final sweep of the charts that I've worked on in my time here at FPF, and here is a miscellaneous grab bag of comments, fixes, and some other things before I go.

Changes proposed in this pull request:
- Adds some comments to help better document some of the code I wrote in the charts
- Made some minor code formatting improvements and cleanup
- Uncovered a bug where the mobile version of the bar chart was actually never being shown (oops my bad)

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing
- Test the charts to make sure there are no regressions.

### General checks

- [x] Linting and tests pass locally
- [x] The website and the changes are functional in Tor Browser
- [x] There is no conflicting migrations
- [x] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [x] The changes are accessible using keyboard and screenreader

### If you made changes to shared templates (e.g. card design, lead media, etc.)

- [x] Verify that it renders correctly in homepage, if applicable
- [x] Verify that it renders correctly in incident index page, if applicable
- [x] Verify that it renders correctly in individual incident page, if applicable
- [x] Verify that it renders correctly in blog index page, if applicable
- [x] Verify that it renders correctly in individual blog page, if applicable
- [x] Verify that it renders correctly in individual special blog page, if applicable

### If you made any frontend change

Mobile version of the bar chart with the slider works again:

Screen Shot 2023-12-29 at 1 32 51 PM

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Thanks so much Daniel for an excellent last pull request. Will get this in ASAP.

**Comment by chigby** [comment]
Not sure I fully understand the mobile bar chart issue. Is there a way to easily reproduce this?

**Comment by dkaoster** [comment]
Before: Mobile version just being a squashed down desktop version

Screenshot 2024-01-02 at 10 34 33 AM

After: Actually using the designs for the mobile version

Screenshot 2024-01-02 at 10 36 32 AM

**Comment by chigby** [comment]
Ahh, I see now! I thought it was more fixing something visually broken with the old one, which I was struggling to break. Thanks!

**Review by chigby — APPROVED** [review]
Changes look good, appreciate the extra documentation and bringing the state of our overall codebase more friendly and maintainable! Thank you!

**Pull request merged**
