### PR TITLE
Fix Chart Downloader

### PR DESCRIPTION
**Pull request by dkaoster**
## Description

Fixes the chart downloader.

Before:
Searched and seized equipment of journalists across the U S

After: 
chart

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

Run the application locally, and try downloading any chart. The downloaded chart should look correct.

### General checks

- [x] Linting and tests pass locally
- [x] The website and the changes are functional in Tor Browser
- [x] There is no conflicting migrations
- [x] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [x] The changes are accessible using keyboard and screenreader

### CODE REVIEW

**Comment by chigby** [comment]
For me, this change does fix the problem of the chart being cropped.

**Comment by chigby** [comment]
Though I am also noticing that sometimes the title can be cut off of the image if the title is too long: 
Camera family reach owner college unit add nearly learn(2)

Not sure if this is related to the same problem of if it's a separate issue.

**Comment by dkaoster** [comment]
> Though I am also noticing that sometimes the title can be cut off of the image if the title is too long:
> 
> Not sure if this is related to the same problem of if it's a separate issue.

This is a separate issue, unfortunately automatic text wrapping is not supported in SVGs, so there are some workarounds but they are all suboptimal. If this is something we want to address I think it'd make sense to cut a new ticket.

**Review by chigby — APPROVED** [review]
Fix works great!

**Pull request merged**
