### PR TITLE
Add field `type_of_denial` under Denial of Access category

### PR DESCRIPTION
**Pull request by chigby**
## Description

Part of #1478 

Changes proposed in this pull request:

Add field `type_of_denial` under Denial of Access category. Field functions similarly to "subpoena statues" or "cases statues" in that it's a multi-select field that stores an array of strings.

**Note**: I didn't add this field to the "performant" CSV API's capabilities yet because I couldn't figure out a straightforward way to implement this type of field, an array of choices that needs to be mapped to their human-readable labels, in pure Django-ORM (my thought was to do a lateral join but it turns out that's not straightforward). There are a couple other fields we have in this format, so I could take the time to figure out how to get this added, and add those others as well, but it will take a little bit more time and I wasn't sure how to prioritize that.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

Make sure that the field operates as we expect in these contexts:

1. Admin. Is it in the right place in the editor UI? Is the default value correct? Does updating and previewing the field work?
2. The front end. Is this field visible in the incident cards? On the incident detail page? Does it display how we want it to? What if there are multiple fields entered?
3. Filtering. Does the field display in the right place on the filter sidebar? Is the UI there correct? When applied, does the filter work correctly for filtering down the list of incidents?
4. API. Does the field render correctly in the JSON API? How about the CSV API?

### Post-deployment actions

In case this PR needs any admin changes or run a management command after deployment, mention it here:

Yes, if we want the field to be filterable, it needs to be added to the Denial of Access category page in the appropriate spot:

image

### General checks

- [x] Linting and tests pass locally
- [x] The website and the changes are functional in Tor Browser
- [x] There is no conflicting migrations
- [x] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [x] The changes are accessible using keyboard and screenreader

### If you made changes to API flow:

- [x] Verify that API responses are correct
- [x] Verify that visualizations using the API endpoints are functional

### If you made changes to incident model metadata

- [x] Verify incident export works correctly
- [x] Verify incident filters are rendered correctly
- [x] Verify incident filters show correct incidents
- [x] Verify categories work
- [x] Verify incidents are discoverable by search

### If you made changes to blog

No changes.

### If you made changes to shared templates (e.g. card design, lead media, etc.)

~~- [ ] Verify that it renders correctly in homepage, if applicable~~ (not applicable)
- [x] Verify that it renders correctly in incident index page, if applicable
- [x] Verify that it renders correctly in individual incident page, if applicable
~~- [ ] Verify that it renders correctly in blog index page, if applicable~~ (not applicable)
~~- [ ] Verify that it renders correctly in individual blog page, if applicable~~ (not applicable)

### If you made changes to email signup flow

No changes.

### If you made changes to "Submit an Incident" form

No changes

### If it's a major change

- [ ] Do the changes need to be tested in a separate staging instance?

### If you made any frontend change

If the PR involves some visual changes in the frontend, it is recommended to add a screenshot of the new visual.

#### Incident index page

image

#### Incident detail page 

image

#### Admin 

image

### CODE REVIEW

**Review by dkaoster — APPROVED** [review]
admin, frontend, filtering, and api all work as described, code is also very clean and easy to understand!

**Comment by SaptakS** [comment]
> I didn't add this field to the "performant" CSV API's capabilities yet because I couldn't figure out a straightforward way to implement this type of field, an array of choices that needs to be mapped to their human-readable labels, in pure Django-ORM (my thought was to do a lateral join but it turns out that's not straightforward). There are a couple other fields we have in this format, so I could take the time to figure out how to get this added, and add those others as well, but it will take a little bit more time and I wasn't sure how to prioritize that.

@chigby do we need to create a separate issue to track this?

**Comment by SaptakS** [comment]
@chigby also there is a migration conflict that needs to be fixed.

**Comment by chigby** [comment]
@SaptakS Added follow-up ticket for API performance https://github.com/freedomofpress/pressfreedomtracker.us/issues/1789

**Pull request merged**
