### PR TITLE
Deploy 2022.01.19

### PR DESCRIPTION
**Pull request by harrislapiroff**
* Upgrade to Wagtail 2.15.2

### Deployment Checklist

Please check off all items before merge

- [x] Verify basic CMS functionality (saving drafts, publishing changes) across content types
- [x] Incident Export
- [x] Incident search
  - [x] Filters
  - [x] Categories
  - [x] Search box
- [ ] "Submit an Incident" form
- [x] Email signup in footer
- [ ] Topic page
  - [ ] Data viz loads
  - [x] Incident info loads
- [x] Category pages

### CODE REVIEW

**Comment by chigby** [comment]
- Submit an incident form did not work: Captcha did not load
- Topic page dataviz not loading: https://staging.pressfreedomtracker.us/george-floyd-protests/

**Comment by chigby** [comment]
Also noticed an error when viewing `PersonPage` objects: https://staging.pressfreedomtracker.us/authors/kio-herrera/

It looks like this happens on production, too? The error is here:
```
django.template.exceptions.TemplateDoesNotExist: common/person_page.html
```

Doesn't look like this error was introduced with the 2.15 upgrade though.

**Review by chigby — APPROVED** [review]
Other than the things mentioned, everything checks out from my POV.

**Comment by harrislapiroff** [comment]
Going to merge and check these issues on prod

**Pull request merged**
