### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by harrislapiroff**
It's finally here!

### CODE REVIEW

**Comment by maeve-fpf** [comment]
Please don't merge this yet, as `develop` will trigger a deploy to staging, which is still on old code -- cleaning that up now. (Merging to `prod` is okay.)

**Comment by harrislapiroff** [comment]
Okay, thanks, @maeve-fpf ! Let me know when I'm OK to merge this. Would like to go through the normal process `feature` -> `staging` -> `prod` for the final tweaks, but can wait a bit.

**Comment by maeve-fpf** [comment]
OK, go ahead and merge to `develop`!

**Comment by harrislapiroff** [comment]
Gonna merge without prod test passing—it'll have to pass again before I merge to prod

**Pull request merged**
