### PR TITLE
Download chart images

### LINKED ISSUE #1609: Download charts as images
Blocked by #1608 

Add a button to charts that allows users to download them as high quality images. These images should include "Source: U.S. Press Freedom Tracker (pressfreedomtracker.us)" rendered within the image. Possibly this credit should be customizable (attn @KAMcCudden)

This is a feature that tracker editors will use themselves—currently they embed a lot of screenshots of charts in newsletters, tweets, etc. This will allow them to generate images with more consistent quality.

This is also a feature that will benefit the tracker by ensuring that when third-party publications reshare tracker charts it includes a credit that leads back to us.

### PR DESCRIPTION
**Pull request by dkaoster**
Blocked by #1614 

closes #1609 

The general approach here is to add a component that wraps any arbitrary component that creates an SVG, and adds functions to allow that SVG to be downloaded using the [canvg](https://canvg.js.org/) library.

Because this does add another dependency to the project, I was wondering what the general process is for vetting new additions to the dependencies, especially being more security conscious.

### CODE REVIEW

**Comment by dkaoster** [comment]
A work in progress draft of what a downloaded chart would look like:

chart

@harrislapiroff @chigby @SaptakS I tried following the designs in figma as much as possible, let me know if there are any other details or things I need to do with this. (Should we have an actual FPF logo embedded in charts?)

**Comment by harrislapiroff** [comment]
Sorry for the delay in feedback: That looks good to me @dkaoster. No need for an FPF logo. Maybe make the URL gray.

Any further work needed on this PR or is it ready for review?

**Comment by dkaoster** [comment]
@harrislapiroff  This one is ready for review but is blocked by #1614 which should be merged first.

**Comment by dkaoster** [comment]
ci pipeline suddenly saying 

```
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/npm',
npm ERR!   dest: '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2023-04-20T21_09_57_782Z-debug-0.log


Exited with code exit status 243
```

any ideas?

**Comment by chigby** [comment]
I think the npm problem will be fixed with this PR: https://github.com/freedomofpress/pressfreedomtracker.us/pull/1631

Sorry about that, a bug I introduced earlier this week without realizing it.

**Comment by chigby** [comment]
I fixed the conflicts on this branch -- I hope nothing broke! Testing it out locally to be sure.

**Comment by dkaoster** [comment]
There's some code that I was using just for testing that can be removed, let me do that

**Review by chigby — APPROVED** [review]
Looks great, signing off on this, let's get it merged!

**Pull request merged**
