### PR TITLE
Implement mobile width strokes for TreeMap component

### PR DESCRIPTION
**Pull request by urlsangel**
Adds mobile width of 3px to TreeMap strokes, adds ternary operator where necessary to select correct width for render.

Resolves note titled "Reduced margins/paddings on category buttons on homepage to match Figma": https://github.com/freedomofpress/pressfreedomtracker.us/projects/4#card-80136414

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Oh, I see the confusion here. Sorry, @urlsangel, that's on me. That card referred to the buttons further down the page. I'll take a look at this PR anyway though and see if it's an improvement we want!

Screen Shot 2022-04-08 at 11 23 21

**Comment by urlsangel** [comment]
@harrislapiroff 

>  That card referred to the buttons further down the page. I'll take a look at this PR anyway though and see if it's an improvement we want!

Oops! The strokes were the wrong width at mobile sizes though, so hopefully not wasted effort!

**Review by chigby — APPROVED** [review]
I think this looks fine (it makes the home page data viz. have less chunky borders between categories) but I understand others have said they want to take a look at it (e.g. @harrislapiroff)

**Comment by harrislapiroff** [comment]
Hm, the original Accurat files are ambiguous on this point. The homepage treemap is skinnier as noted by @urlsangel, but the treemap in the charts guidelines doesn't change from mobile to desktop. I'll merge this, but adding this comment for posterity should we decide to revert in the future.

**Pull request merged**
