### PR TITLE
1239 About page

### LINKED ISSUE #1239: About page (Special Page)
[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3672%3A50783)

The about page is currently a "Special Page" type. Let's expand the special page type to support the necessary features.

- [x] Add the necessary stream blocks to render tables on the about page with all the data the design will require
- [x] Create template and styles to render the about page design

### PR DESCRIPTION
**Pull request by urlsangel**
Adds `InfoTableBlock` to common blocks.
Adds `InfoTableBlock` to `SimplePage` body field.
Adds html template for `SimplePage`
Adds `InfoTableBlock` template and sub-templates.

@harrislapiroff @chigby @SaptakS 

I've used the same markup and classes that were already in the codebase for the `list-table` element, as this looks very similar to what's in the figma design.

The current iteration requires more polish to match the design, but I'm wary of overlap here - it would be great if I could get a review on this before I start again tomorrow?

I can add extend the `list-table` element in SASS to make it match the design, but wasn't sure if some of this was already a work in progress on another branch?

### CODE REVIEW

**Comment by urlsangel** [comment]
This is what it's currently looking like just using the `list-table` element.
localhost_8000_about_ (1)
localhost_8000_about_ (2)
localhost_8000_about_

**Comment by urlsangel** [comment]
Implemented styles as per Figma, except the negative margin on the table at desktop size, as that looks really weird when the center column stops at 1440px wide - looks a bit broken IMO.

Here's what the about page looks like on my local dev:

### Mobile
localhost_8000_about_ (3)

### Tablet
localhost_8000_about_ (4)

### Desktop
localhost_8000_about_ (5)

**Comment by SaptakS** [comment]
Looking into this.

**Review by urlsangel — COMMENTED** [review]
Hey @SaptakS 

https://github.com/freedomofpress/pressfreedomtracker.us/pull/1244/commits/72bb2865bfaca9df987169709f391489db8ec592#diff-ba08fb48e56086009433b889c4d23b2e1152b9bae98a8feb3832c13aab0894bbR1

I'd used a generic term for the body content ("section-body") as I thought this could then be re-used on other pages?

**Comment by SaptakS** [comment]
@urlsangel With experience from implementing the designs, I have noticed that generic styling doesn't work well for most cases, so section-body sounded too generic a name, hence I replaced it with something more specific for the simple pages. That's how we have gone about implementing most of the other pages to enable fine tuning wherever necessary.

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
