### PR TITLE
Replaces node-sass with dart-sass

### PR DESCRIPTION
**Pull request by SaptakS**
- Also fixes some sass related issues in the code

Refs freedomofpress/fpf-www-projects#173

PS: There are certain selector rules that are throwing a warning right now. Mainly the ones where a color name is appended in the selector. 

```
node_1        | WARNING: You probably don't mean to use the color value yellow in interpolation here.
node_1        | It may end up represented as yellow, which will likely produce invalid CSS.
node_1        | Always quote color names when using them as strings or map keys (for example, "yellow").
node_1        | If you really want to use the color value here, use '"" + $name'.
node_1        |
node_1        |     _
node_1        | 127 _     .incident--#{$name}
node_1        |     _                  ^^^^^
node_1        |     _
node_1        |     client/common/sass/_incident.sass 127:15  @import
node_1        |     stdin 47:9                                root stylesheet

```

### CODE REVIEW

**Comment by chigby** [comment]
@SaptakS I was playing around with this locally and I think I figured out how to fix the warnings, do you want me to push those changes?

**Comment by SaptakS** [comment]
Sure!

**Comment by SaptakS** [comment]
The above commits look good to me for removing of warnings

**Review by chigby — APPROVED** [review]
I'm considering this ready to merge. The functionality of the new sass package worked fine, per my testing.

**Pull request merged**
