### PR TITLE
Legal order metadata updates

### LINKED ISSUE #1512: Subpoena metadata changes
Very similar to arrest metadata changes. [Spec out more soon]

### PR DESCRIPTION
**Pull request by chigby**
Fixes #1512 

This pull request adds new legal-order-related model fields to `IncidentPage` in accordance with the above issue ([and the relevant spec notes](https://docs.google.com/document/d/1OLYe27H2_OvmJoEtpjuU1hEiYglaD36ZofNUMAgTI-s/edit#)). I've tried to compartmentalize all the changes into somewhat legible commits, so please see those for more information. I have tried not to remove any model fields, so the old data will remain in a deprecated state until we're sure everything is good, then it should be removed. 

I've also modified slightly the process for generating links to the category field data on the incident cards and details page. Previously, data values were rendered as hyperlinks with a querystring appropriate for filtering all incidents by that value, e.g. `href="/all-incidents/?legal_order_target=JOURNALIST`. This would correctly filter the list of incidents on the incident index page. However, the filter sidebar would not have the appropriate category highlighted and its filters show, including the one that has a populated value in it. I've updated the link-making code to add support for this with an additional querystring key/value containing the name of the category, e.g.: `href="/all-incidents/?categories=Subpoenas&legal_order_target=JOURNALIST`. This is not part of the original issue but it made the links a lot more usable for me.

### Testing and acceptance

When testing this out locally, the filters will not appear in the sidebar unless you manually add them to the category page with the slug `subpoena`, or unless you delete and re-create your development data from scratch with something like:

```shell
$ docker compose rm -f postgresql
$ docker compose run --rm python manage.py migrate
$ docker compose run --rm python manage.py createdevdata
```

Doing this will also populate the incidents with some sample data in the new fields so you can explore them, so I recommend it. Though it will remove all previous data on your local db.

#### Legal Order Importer

The legal order import tool, which takes a CSV with specific data columns and updates the corresponding incident pages, is available in the admin under Tools > Legal Order Import.

The CSV format that this accepts is based on the [metadata update sheet](https://docs.google.com/spreadsheets/d/1DLnF1Xk3YORu05YIvBZKRothXXP8CAYgx7i4yPZae-A/edit#gid=308294336) provided by the PFT team (a work in progress currently). This document is not completely compatible with the importer as of my writing this, so for testing it will be helpful to have a CSV of your own, but there are a lot of possibilities for the data, so it will be helpful to have one you can edit so that you can test out various scenarios.

The column that determines which incident will be updated is `slug`, which should contain the URL of the incident. From there, the `venue` and `target` columns can contain data that will be applied to the `legal_order_venue` and `legal_order_target` respectively. The data in the columns should be the _label_ (not the value) of the desired choice.

Beyond that, data for each legal order is stored across columns with names prefixed by `legal_order1`, `legal_order2`, and so on. Each of these legal orders can also have multiple status/date pairs in, for example, columns called `legal_order1_status1`, `legal_order1_status2` (with the corresponding `legal_order1_date2`, etc.). 

I've [attached an example with some of these filled out](https://github.com/freedomofpress/pressfreedomtracker.us/files/11193294/subpoenas-short.csv). It will need to be updated for your specific dev environment as the `slug` column will not correspond to anything you have. It can be used as a basis for making more, so please experiment with different values to make sure they're properly handled by the importer.

### Further work

This PR is ready for code review but should not be merged until we are ready to update the existing production data from the old format to the new format.

### CODE REVIEW

**Comment by chigby** [comment]
Pushed some more changes to this branch to support an Admin page for importing legal order data as a CSV modeled on the format of [this document](https://docs.google.com/spreadsheets/d/1DLnF1Xk3YORu05YIvBZKRothXXP8CAYgx7i4yPZae-A/edit#gid=308294336). This feature is found in the admin sidebar under Tools > Legal Order Import (http://localhost:8000/admin/legal_orders/import/) and ought to be poked a little in testing.

**Review by SaptakS — APPROVED** [review]
I tested the code and import tool. Looks good to me.

**Comment by chigby** [comment]
I think the next step in this process is to deploy this branch to the experimental cluster, try the import tool against the latest sanitized version of the production database, and let the PFT team inspect the results

**Comment by chigby** [comment]
According to PFT people, and to me, this is looking good on the experimental server. I'm going to merge, and we can continue to check in on this on staging.

**Pull request merged**
