### PR TITLE
Tweak spacing issues around tags on incident cards

### PR DESCRIPTION
**Pull request by urlsangel**
Apologies @SaptakS - I know you just reviewed and merged a tweak for these!

After doing some browser testing I've tweaked a couple of CSS properties for a better layout of these tags.

### CODE REVIEW

**Comment by SaptakS** [comment]
This seems to remove the margin from the top of the tags, which is needed based on the figma design. Maybe you can add a margin top in `.tag-list`?

**Comment by urlsangel** [comment]
> This seems to remove the margin from the top of the tags, which is needed based on the figma design. Maybe you can add a margin top in `.tag-list`?

Hey @SaptakS 

I think this is a bit whack-a-mole, as the top margin isn't necessary in some contexts, but might be in others. I'll do some local dev later this afternoon to try to capture all contexts and make the list look good wherever it's used - ignore this PR for now 👍

**Comment by SaptakS** [comment]
I feel applying the top margin on the parent ul instead of individual li should actually fix for almost all cases if I am not wrong.

**Comment by urlsangel** [comment]
> I feel applying the top margin on the parent ul instead of individual li should actually fix for almost all cases if I am not wrong.

@SaptakS - yep, I think that works for all the use cases I can see , I've added that now 👍

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
